//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAE.WebUI.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;x&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template....
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed code:.
        /// </summary>
        public static string EmbedCode {
            get {
                return ResourceManager.GetString("EmbedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username:.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit image within&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string FitImageWithin {
            get {
                return ResourceManager.GetString("FitImageWithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Albums.
        /// </summary>
        public static string GetAlbums {
            get {
                return ResourceManager.GetString("GetAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide template editor.
        /// </summary>
        public static string HideTemplateEditor {
            get {
                return ResourceManager.GetString("HideTemplateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include unlisted albums / Password:.
        /// </summary>
        public static string IncludeUnlistedAlbumsChecked {
            get {
                return ResourceManager.GetString("IncludeUnlistedAlbumsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include unlisted albums.
        /// </summary>
        public static string IncludeUnlistedAlbumsUnchecked {
            get {
                return ResourceManager.GetString("IncludeUnlistedAlbumsUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picasa Web Album Exporter, Export Picasa Albums as HTML with Captions, Embed Picasa Album in Your Blog.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;pixels.
        /// </summary>
        public static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo caption.
        /// </summary>
        public static string PlaceholderCaption {
            get {
                return ResourceManager.GetString("PlaceholderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential number of the photo in the album.
        /// </summary>
        public static string PlaceholderCounter {
            get {
                return ResourceManager.GetString("PlaceholderCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file name with an extension.
        /// </summary>
        public static string PlaceholderFileName {
            get {
                return ResourceManager.GetString("PlaceholderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized according to your settings image URL.
        /// </summary>
        public static string PlaceholderImage {
            get {
                return ResourceManager.GetString("PlaceholderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original full-size image URL.
        /// </summary>
        public static string PlaceholderOriginal {
            get {
                return ResourceManager.GetString("PlaceholderOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the photo page on Picasa website.
        /// </summary>
        public static string PlaceholderPicasaUrl {
            get {
                return ResourceManager.GetString("PlaceholderPicasaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview generated HTML....
        /// </summary>
        public static string PreviewHtml {
            get {
                return ResourceManager.GetString("PreviewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select album:.
        /// </summary>
        public static string SelectAlbum {
            get {
                return ResourceManager.GetString("SelectAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Picasa web albums as &lt;b&gt;HTML&lt;/b&gt;, &lt;b&gt;XML&lt;/b&gt;, &lt;b&gt;BBCode&lt;/b&gt;, etc..
        /// </summary>
        public static string SiteFeature1 {
            get {
                return ResourceManager.GetString("SiteFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;to your friends.
        /// </summary>
        public static string SiteFeature10 {
            get {
                return ResourceManager.GetString("SiteFeature10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export &lt;b&gt;unlisted albums&lt;/b&gt; (with a password).
        /// </summary>
        public static string SiteFeature2 {
            get {
                return ResourceManager.GetString("SiteFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &lt;b&gt;your own HTML template&lt;/b&gt; or use the default one.
        /// </summary>
        public static string SiteFeature3 {
            get {
                return ResourceManager.GetString("SiteFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &lt;b&gt;any size&lt;/b&gt; for landscape or portrait orientation.
        /// </summary>
        public static string SiteFeature4 {
            get {
                return ResourceManager.GetString("SiteFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include photo &lt;b&gt;captions&lt;/b&gt;, &lt;b&gt;full-size&lt;/b&gt; images and other info.
        /// </summary>
        public static string SiteFeature5 {
            get {
                return ResourceManager.GetString("SiteFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed in &lt;b&gt;your blog&lt;/b&gt; (WordPress, LiveJournal, etc.).
        /// </summary>
        public static string SiteFeature6 {
            get {
                return ResourceManager.GetString("SiteFeature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly &lt;b&gt;preview&lt;/b&gt; exported HTML.
        /// </summary>
        public static string SiteFeature7 {
            get {
                return ResourceManager.GetString("SiteFeature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;mailto:dusiadev@gmail.com?Subject=[PAE]&quot;&gt;Contact developer&lt;/a&gt; to report problem or &lt;b&gt;request new feature&lt;/b&gt;.
        /// </summary>
        public static string SiteFeature8 {
            get {
                return ResourceManager.GetString("SiteFeature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread the word:&amp;nbsp;.
        /// </summary>
        public static string SiteFeature9 {
            get {
                return ResourceManager.GetString("SiteFeature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picasa Web Album Exporter.
        /// </summary>
        public static string SiteHeader {
            get {
                return ResourceManager.GetString("SiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Changes.
        /// </summary>
        public static string UndoChanges {
            get {
                return ResourceManager.GetString("UndoChanges", resourceCulture);
            }
        }
    }
}
